
services:
  backend:
    build:
      context: ./backend/
      dockerfile: docker/dockerfile.backend
    image: backend:latest
    ports:
      - "9000:8000"
    env_file:
      - .env
    volumes:
      - ./backend:/home/app
<<<<<<< HEAD
    command: python manage.py runserver 0.0.0.0:8000
    restart: always
    depends_on:
      - db
=======
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload 
    restart: always
>>>>>>> e4a0313538aa7782bc9080033b9bbd95ea8de4d0
    
  db:
    image: postgres:15-alpine
    ports:
<<<<<<< HEAD
      - "5432:5432"
    restart: always
    env_file:
      - .env
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
=======
      - "5430:5432"
    restart: always
    expose:
      - "5430"
    env_file:
      - .env
>>>>>>> e4a0313538aa7782bc9080033b9bbd95ea8de4d0
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
<<<<<<< HEAD
  postgres_data:
=======
  postgres_data:

>>>>>>> e4a0313538aa7782bc9080033b9bbd95ea8de4d0
