# Generated by Django 5.1.7 on 2025-03-26 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Basic', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basic_village',
            name='village_name',
            field=models.CharField(max_length=100),
        ),
    ]
